### ISSUE TITLE
Help using Actix Redis Session with Heroku-Redis

### ISSUE THREAD

**Issue by hbina** [actix/actix-extras#17]
I can't seem to connect to it. I keep getting this error printed every second.

```
2020-03-05T14:36:50.954618+00:00 app[web.1]: [2020-03-05T14:36:50Z ERROR actix_redis::redis] Can not connect to redis server: Failed resolving hostname: no record found for name: redis type: AAAA class: IN
```

The setup guide in Heroku documentation only says you need to grab the `REDIS_URL` from env variable and you are good to go.

Here's how I set it up,

```rust
let redis_url = env::var("REDIS_URL").expect("REDIS_URL env variable cannot be found.");
    db::init();
    let mut listenfd = ListenFd::from_env();
    let mut server = HttpServer::new(move || {
        App::new()
            .wrap(RedisSession::new(format!("{}", redis_url), &[0; 32]))
            .service(index)
            .configure(user::init_routes)
            .configure(auth::init_routes)
            .configure(organ::init_routes)
    });

```

Where, REDIS_URL is something like ...

```
REDIS_URL: redis://h:skdhjgkldfshgkldfhlgfdg23affde@ac-23-3232-3.compute-1.amazonaws.com:12345
```

I assume the stuff after `:` is the port? Nonetheless, I can't find more information about this. Or where to look.

**Comment by BartWillems** [comment]
For some reason, you can't prepend your redis url with `redis://`, specifying Redis database also seem to be unsupported

**Comment by mbresson** [comment]
Hi @hbina.
I don't know if you have already solved your issue, but I ran into a similar problem. I'm not on Heroku, but my Rust actix application was running inside a docker container, and I got the same error message as you.

I found a solution by looking at this part of the logs: `<trust_dns_resolver::error::ResolveError as core::convert::From<trust_dns_resolver::error::ResolveErrorKind>>::from`…

Actix-redis seems to use the crate [trust-dns-resolver](https://crates.io/crates/trust-dns-resolver) to resolve names.
This crate has the specific warning:

```This is a 100% in process DNS resolver. It does not use the Host OS' resolver. If what is desired is to use the Host OS' resolver, generally in the system's libc, then the std::net::ToSocketAddrs variant over &str should be used.```

Docker applications use an internal DNS resolver provided by docker, and it seems that trust-dns-resolve is bypassing it.

I don't know the details of how this works, but I found a workaround: I resolve the address of the redis server before passing it to RedisSession::new.

Here is a rough example of how to make it work:

```
use std::net::ToSocketAddrs;

...

let redis_url = env::var("REDIS_URL").expect("REDIS_URL env variable cannot be found.");
// HERE you should strip the redis:// prefix from your redis_url

let redis_addr = redis_url.to_socket_addrs().unwrap().next().unwrap();

...

    .wrap(RedisSession::new(redis_addr.to_string(), &private_key))
```

(the to_socket_addrs().unwrap().next().unwrap() creates an iterator on resolved IP addresses and takes the first result)

You may need to transform your redis_url further by removing the `redis:// prefix` and maybe the `h:skdhjgkldfshgkldfhlgfdg23affde@` part too but I don't know since I'm not on heroku.
Good luck!

**Comment by robjtede** [comment]
now that the sessions crate supports a redis-rs backend, this fix is out-of-scope for actix-redis

**Comment by 0mvar** [comment]
I'm facing this issue: I'm using actix-redis: 0.12.0 on a heroku server.

```
2022-11-13T03:19:14.456925+00:00 app[web.1]: [2022-11-13T03:19:14Z ERROR actix_redis::redis] Can not connect to redis server: Failed to resolve hostname
```

> now that the sessions crate supports a redis-rs backend, this fix is out-of-scope for actix-redis
