### ISSUE TITLE
actix_cors blocks requests that should be allowed

### ISSUE THREAD

**Issue by CapableWeb** [actix/actix-extras#286]
## Expected Behavior

If I have app.example.com as a whitelisted Origin but both the backend + frontend is loaded from app2.example.com, request should be allowed.

## Current Behavior

If I have app.example.com as a whitelisted Origin but both the backend + frontend is loaded from app2.example.com, requests are blocked, even though Host + Origin is the same. Browsers allow these requests to happen (no OPTIONS request sent, as Origin + Host is the same), but actix_cors decides to forcefully block the request.

Relevant code from actix_cors:

https://github.com/actix/actix-extras/blob/1561bda82268931edb070501413a46337ed71290/actix-cors/src/inner.rs#L73-L99

## Possible Solution

actix_cors should not forcefully cancel/error on requests where Origin and Host is the same header. In fact, if there is no OPTIONS request, actix_cors should not care about the actual request at all, besides setting the right headers on the Response. As it stands today, actix_cors is trying to be overly protective of responses while it doesn't add anything regarding security.

**Comment by robjtede** [comment]
The CORS protocol is activated by the presence of an Origin header. For same origin requests, it should not be sent. That or add the required domain to the allow list.

**Comment by robjtede** [comment]
Firstly, the CORS protocol says nothing about trying to match `Origin` and `Host` to and allowing the request to pass and there's no precedent in other libraries I've looked at to add this hidden behavior; so, that cannot be part of the solution here.

Sadly, the Fetch spec where CORS is defined is very targetted at clients and not servers:

> Ultimately server developers have a lot of freedom in how they handle HTTP responses...

Since it's concern is only on visibility of response data, it gives almost no guidance on how servers should handle these requests; only that the client should not be able to read responses without Access-Control-Allow-* headers.

Given that, I understand your point now, that instead of processing the request and serving the response without the headers, we [simply block the request](https://github.com/actix/actix-extras/blob/master/actix-cors/src/middleware.rs#L186). Plus the example of "this cURL command should work even without the origin being allowed" is true and compelling (though not because of the Host header).

So I think some sort of change is needed. The question is do we make this an opt-in, opt-out, or always on behavior. I need to verify some browser behaviors but I suspect you are right that this can be allowed by default. I'll get back to you later today...

**Comment by robjtede** [comment]
Yeah sounds good.
